server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
    
zuul: 
  prefix: /zuule #设置统一公共前缀
  ignored-services: "*" #忽略原真实名称
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/** # 替换microservicecloud-dept
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 

info:
  app.name: atguigu-microcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$